### ISSUE TITLE
Sever crash bug

### ISSUE THREAD

**Issue by FirstCodeReviewer** [Luka967/OgarII#30]
Occured on a clean copy of OgarII.
It happens when someone is on spectate and the last player dies lets say e.g. to a mothercell.

[FATAL] TypeError: Cannot read property 'viewArea' of null
    at Player.updateViewArea (src/worlds/Player.js:90:46)
    at World.liveUpdate (src/worlds/World.js:361:20)
    at World.update (src/worlds/World.js:243:50)
    at ServerHandle._onTick (src/ServerHandle.js:173:29)
    at Ticker._tick (src/primitives/Ticker.js:43:30)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

**Comment by SuperOP535** [comment]
i think the world gets deleted because last player has left and it does not count spectators as players...?

**Comment by Luka967** [comment]
will be fixed in 1.2.0
