### ISSUE TITLE
Chat issue

### ISSUE THREAD

**Issue by Faris90** [Luka967/OgarII#31]
@ 2018-12-07 15:37:01.374 [FATAL] TypeError: Cannot read property 'onChatMessage' of null

    at ChatChannel.broadcast (/app/src/sockets/ChatChannel.js:53:42)

    at Connection.onChatMessage (/app/src/sockets/Connection.js:92:36)

    at LegacyProtocol.onSocketMessage (/app/src/protocols/LegacyProtocol.js:115:33)

    at Connection.onSocketMessage (/app/src/sockets/Connection.js:69:51)

    at onServerMessage (/rbd/pnpm-volume/a62882a5-26d5-4c42-943c-2935f797d5df/node_modules/.registry.npmjs.org/uws/10.148.1/node_modules/uws/uws.js:21:15)

2018-12-07 15:37:01.380 [ERROR] uncaught exception - process is terminating

2018-12-07 15:37:02.138 [INFO] command stream open

2018-12-07 15:37:02.145 [INFO] starting

2018-12-07 15:37:02.161 [INFO] ticker begin

2018-12-07 15:37:02.161 [INFO] OgarII 1.1.12

2018-12-07 15:37:02.164 [INFO] listener open at 3000

@ 2018-12-07 15:37:03.672 [FATAL] TypeError: Cannot read property 'onChatMessage' of null

    at ChatChannel.broadcast (/app/src/sockets/ChatChannel.js:53:42)

    at Connection.onChatMessage (/app/src/sockets/Connection.js:92:36)

    at LegacyProtocol.onSocketMessage (/app/src/protocols/LegacyProtocol.js:115:33)

    at Connection.onSocketMessage (/app/src/sockets/Connection.js:69:51)

    at onServerMessage (/rbd/pnpm-volume/a62882a5-26d5-4c42-943c-2935f797d5df/node_modules/.registry.npmjs.org/uws/10.148.1/node_modules/uws/uws.js:21:15)

2018-12-07 15:37:03.673 [ERROR] uncaught exception - process is terminating

**Comment by Luka967** [comment]
will be dealt with in the rewrite.

**Comment by Luka967** [comment]
Resolved in 1.3.2
