### ISSUE TITLE
doesnt start.

### ISSUE THREAD

**Issue by freaky767** [Luka967/OgarII#4]
when i try to start it, it gives the error 
"SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)"

**Comment by freaky767** [comment]
tried reinstalling, same error

**Comment by Luka967** [comment]
Should be fixed with the latest commit
