### ISSUE TITLE
Official Agar.io private server

### ISSUE THREAD

**Issue by TeiBri** [Luka967/OgarII#55]
Please how to create OFFICIAL agar.io private server. How?

**Comment by Faris90** [comment]
What do you mean?

**Comment by TeiBri** [comment]
Original https://agar.io/?ip=127.0.0.1
                           
Original website agar.io please !!
https://m.youtube.com/watch?v=ptcOHb13wio&t=1s

**Comment by TeiBri** [comment]
You know?

**Comment by KevinGHB** [comment]
He mean how to create a server and join it with the agar.io client. Also I can't join the discord server, is the link expired ?

**Comment by TeiBri** [comment]
Yes! :DDD KevinGHB.

**Comment by Faris90** [comment]
Download the recent version

**Comment by TeiBri** [comment]
and it works on the original agar.io?

**Comment by TeiBri** [comment]
C:\Users\uzivatel\Desktop\OgarII-master\node_modules\uws\uws.js:40
            throw new Error('Compilation of µWebSockets has failed and there is no pre-compiled binary ' +
            ^

Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
    at C:\Users\uzivatel\Desktop\OgarII-master\node_modules\[4muws[24m\uws.js:40:19
    at Object.<anonymous> (C:\Users\uzivatel\Desktop\OgarII-master\node_modules\[4muws[24m\uws.js:44:3)
[90m    at Module._compile (internal/modules/cjs/loader.js:1158:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:1002:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:901:14)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1044:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:77:18)[39m
    at Object.<anonymous> (C:\Users\uzivatel\Desktop\OgarII-master\src\sockets\Listener.js:1:19)
[90m    at Module._compile (internal/modules/cjs/loader.js:1158:30)[39m
PS C:\Users\uzivatel\Desktop\OgarII-master\cli>


What!? :/

**Comment by TeiBri** [comment]
How to reinstall uws?

**Comment by giulian2003** [comment]
I had the same problem and fixed it by using Node.js version 8.
