### ISSUE TITLE
Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.

### ISSUE THREAD

**Issue by NathanGinette** [Luka967/OgarII#70]
D:\agar io\OgarII-master\cli>node index.js
module.js:549
    throw err;
    ^

Error: Cannot find module 'uws'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\agar io\OgarII-master\src\sockets\Listener.js:1:81)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

D:\agar io\OgarII-master\cli>

**please, help me**

**Comment by DeadLord1337** [comment]
@NathanGinette replace "uws" module with "ws"

**Comment by Anon10104** [comment]
@DeadLord1337 layman term it to me im stupid im also having the same issue
