### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by TopoR1** [Luka967/OgarII#9]
@ 2018-02-19 17:45:47.043 [FATAL] TypeError: Cannot read property 'name' of unde
fined
at getLeaderboardData (C:\Users\Administrator\Desktop\FFA\версия 2\OgarII-ma
ster\src\gamemodes\FFA.js:51:36)
at leaderboard.map (C:\Users\Administrator\Desktop\FFA\версия 2\OgarII-maste
r\src\gamemodes\FFA.js:36:48)
at Array.map ()
at FFA.sendLeaderboard (C:\Users\Administrator\Desktop\FFA\версия 2\OgarII-m
aster\src\gamemodes\FFA.js:36:34)
at Connection.update (C:\Users\Administrator\Desktop\FFA\версия 2\OgarII-mas
ter\src\sockets\Connection.js:205:43)
at Listener.update (C:\Users\Administrator\Desktop\FFA\версия 2\OgarII-maste
r\src\sockets\Listener.js:109:20)
at ServerHandle._onTick (C:\Users\Administrator\Desktop\FFA\версия 2\OgarII-
master\src\ServerHandle.js:152:23)
at Ticker._tick (C:\Users\Administrator\Desktop\FFA\версия 2\OgarII-master\s
rc\primitives\Ticker.js:43:30)
at ontimeout (timers.js:458:11)
at tryOnTimeout (timers.js:296:5)
2018-02-19 17:45:47.043 [ERROR] uncaught exception - process is terminating
Restarting server

Appears unexpectedly, at any time. Please correct!

**Comment by Luka967** [comment]
I'll try to get it when I get time
In the meantime you can try catching it again or at least provide a log with a couple things on it before it throws

**Comment by Luka967** [comment]
Fixed in a quite old commit. It  a problem with player bot destruction.
